# Generated by Django 2.0.6 on 2018-06-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='tpye',
            new_name='type',
        ),
    ]
