# Generated by Django 2.0.6 on 2018-06-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
                ('flag', models.BooleanField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'detials',
            },
        ),
        migrations.CreateModel(
            name='Ele_Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=10)),
                ('material', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('flag', models.BooleanField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='detial',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_flow.Ele_Overview'),
        ),
    ]
