# Generated by Django 2.0.6 on 2018-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detial',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ele_overview',
            name='number',
            field=models.IntegerField(),
        ),
    ]
