# Generated by Django 2.0.6 on 2018-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0002_auto_20180620_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detial',
            name='flag',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='ele_overview',
            name='flag',
            field=models.BooleanField(default=1),
        ),
    ]
