# Generated by Django 2.0.6 on 2018-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0004_auto_20180620_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ele_overview',
            name='flag',
            field=models.NullBooleanField(),
        ),
    ]
